apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: core.harbor.domain:30609/myregistry/chatbot
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: cb-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: chatbot
  ports:
    - port: 8000
      targetPort: 8000
